#!/usr/bin/env python3
"""
Code Generator - Generates working Python scripts from agent specifications.

This module creates production-ready code including:
- Skill modules with proper error handling
- Helper scripts
- Configuration files
- Test suites
"""

import json
import logging
import os
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Optional

# Configure logging
logging.basicConfig(
    level=getattr(logging, os.getenv("WORLD_CEO_LOG_LEVEL", "INFO")),
    format="%(asctime)s - %(name)s - %(levelname)s - %(message)s"
)
logger = logging.getLogger("code_generator")


@dataclass
class CodePackage:
    """Collection of generated code files."""
    skill_py: str
    skill_md: str
    config_py: str
    utils_py: str
    test_py: str
    requirements_txt: str
    readme_md: str


class CodeGenerator:
    """Generates complete agent code from specifications."""
    
    def __init__(self, output_dir: Optional[str] = None):
        self.output_dir = Path(output_dir or os.getenv("WORLD_CEO_OUTPUT_DIR", "./output"))
        self.output_dir.mkdir(parents=True, exist_ok=True)
    
    def _slugify(self, name: str) -> str:
        """Convert name to Python-friendly identifier."""
        return name.lower().replace(" ", "_").replace("-", "_")
    
    def _classify(self, name: str) -> str:
        """Convert name to PascalCase class name."""
        return "".join(word.capitalize() for word in name.replace("-", "_").split("_"))
    
    def generate_skill_py(self, agent_name: str, spec: dict) -> str:
        """Generate main skill module."""
        slug = self._slugify(agent_name)
        class_name = self._classify(slug)
        date_str = datetime.now().strftime("%Y-%m-%d")
        desc = spec.get("description", "No description provided.")
        
        lines = [
            '#!/usr/bin/env python3',
            f'"""',
            f'{agent_name} Skill - Main implementation module.',
            f'',
            f'Generated by WORLD CEO on {date_str}',
            f'"""',
            f'',
            f'import json',
            f'import logging',
            f'import os',
            f'from typing import Any, Dict, List, Optional',
            f'from dataclasses import dataclass',
            f'from datetime import datetime',
            f'',
            f'# Configure logging',
            f'logging.basicConfig(',
            f'    level=getattr(logging, os.getenv("{slug.upper()}_LOG_LEVEL", "INFO")),',
            f'    format="%(asctime)s - %(name)s - %(levelname)s - %(message)s"',
            f')',
            f'logger = logging.getLogger("{slug}")',
            f'',
            f'',
            f'@dataclass',
            f'class TaskResult:',
            f'    """Standard result structure for all operations."""',
            f'    success: bool',
            f'    data: Optional[Any] = None',
            f'    error: Optional[str] = None',
            f'    timestamp: str = None',
            f'    ',
            f'    def __post_init__(self):',
            f'        if self.timestamp is None:',
            f'            self.timestamp = datetime.now().isoformat()',
            f'    ',
            f'    def to_dict(self) -> Dict:',
            f'        return {{',
            f'            "success": self.success,',
            f'            "data": self.data,',
            f'            "error": self.error,',
            f'            "timestamp": self.timestamp',
            f'        }}',
            f'',
            f'',
            f'class {class_name}Skill:',
            f'    """',
            f'    {agent_name} skill implementation.',
            f'    ',
            f'    {desc}',
            f'    """',
            f'    ',
            f'    def __init__(self, config: Optional[Dict] = None):',
            f'        """',
            f'        Initialize the skill.',
            f'        ',
            f'        Args:',
            f'            config: Optional configuration dictionary',
            f'        """',
            f'        self.config = config or {{}}',
            f'        self.name = "{agent_name}"',
            f'        self.version = "0.1.0"',
            f'        logger.info(f"Initialized {{self.name}} v{{self.version}}")',
            f'    ',
            f'    def execute(self, task: str, params: Optional[Dict] = None) -> TaskResult:',
            f'        """',
            f'        Execute a task with the given parameters.',
            f'        ',
            f'        Args:',
            f'            task: Task identifier',
            f'            params: Task parameters',
            f'            ',
            f'        Returns:',
            f'            TaskResult with success status and data',
            f'        """',
            f'        params = params or {{}}',
            f'        logger.info(f"Executing task: {{task}}")',
            f'        ',
            f'        try:',
            f'            # Route to appropriate handler',
            f'            handler = getattr(self, f"_handle_{{task}}", self._handle_default)',
            f'            result = handler(params)',
            f'            return TaskResult(success=True, data=result)',
            f'            ',
            f'        except Exception as e:',
            f'            logger.error(f"Task failed: {{e}}")',
            f'            return TaskResult(success=False, error=str(e))',
            f'    ',
            f'    def _handle_default(self, params: Dict) -> Any:',
            f'        """Default handler for unrecognized tasks."""',
            f'        raise NotImplementedError(f"Task handler not implemented")',
            f'    ',
            f'    def _handle_example(self, params: Dict) -> Dict:',
            f'        """',
            f'        Example task handler.',
            f'        ',
            f'        Args:',
            f'            params: Task parameters',
            f'            ',
            f'        Returns:',
            f'            Result dictionary',
            f'        """',
            f'        # TODO: Implement actual logic',
            f'        return {{"status": "example", "params": params}}',
            f'    ',
            f'    def health_check(self) -> TaskResult:',
            f'        """',
            f'        Perform health check.',
            f'        ',
            f'        Returns:',
            f'            TaskResult indicating health status',
            f'        """',
            f'        try:',
            f'            # TODO: Add actual health checks',
            f'            return TaskResult(success=True, data={{"status": "healthy"}})',
            f'        except Exception as e:',
            f'            return TaskResult(success=False, error=str(e))',
            f'',
            f'',
            f'def main():',
            f'    """CLI entry point."""',
            f'    import argparse',
            f'    ',
            f'    parser = argparse.ArgumentParser(description="{agent_name} Skill")',
            f'    parser.add_argument("--task", "-t", required=True, help="Task to execute")',
            f'    parser.add_argument("--params", "-p", help="JSON parameters")',
            f'    parser.add_argument("--health", action="store_true", help="Run health check")',
            f'    ',
            f'    args = parser.parse_args()',
            f'    ',
            f'    skill = {class_name}Skill()',
            f'    ',
            f'    if args.health:',
            f'        result = skill.health_check()',
            f'    else:',
            f'        params = json.loads(args.params) if args.params else {{}}',
            f'        result = skill.execute(args.task, params)',
            f'    ',
            f'    print(json.dumps(result.to_dict(), indent=2))',
            f'',
            f'',
            f'if __name__ == "__main__":',
            f'    main()',
        ]
        
        return '\n'.join(lines)
    
    def generate_skill_md(self, agent_name: str, spec: dict) -> str:
        """Generate SKILL.md documentation."""
        slug = self._slugify(agent_name)
        class_name = self._classify(slug)
        desc = spec.get("description", "No description provided.")
        
        lines = [
            f'# {agent_name} Skill',
            f'',
            f'## Overview',
            f'',
            f'{desc}',
            f'',
            f'## Installation',
            f'',
            f'```bash',
            f'pip install -r requirements.txt',
            f'```',
            f'',
            f'## Usage',
            f'',
            f'### Python API',
            f'',
            f'```python',
            f'from {slug}_skill import {class_name}Skill',
            f'',
            f'skill = {class_name}Skill()',
            f'result = skill.execute("task_name", {{"param": "value"}})',
            f'```',
            f'',
            f'### CLI',
            f'',
            f'```bash',
            f'python {slug}_skill.py --task task_name --params \'{{"param": "value"}}\'',
            f'```',
            f'',
            f'## Configuration',
            f'',
            f'Environment variables:',
            f'- `{slug.upper()}_LOG_LEVEL`: Logging level (DEBUG, INFO, WARN, ERROR)',
            f'- `{slug.upper()}_TIMEOUT`: Request timeout in seconds',
            f'',
            f'## Tasks',
            f'',
            f'### example',
            f'',
            f'Example task description.',
            f'',
            f'**Parameters**:',
            f'- `param1`: Description',
            f'- `param2`: Description',
            f'',
            f'**Returns**:',
            f'- `status`: Task status',
            f'- `data`: Result data',
            f'',
            f'## Error Handling',
            f'',
            f'All tasks return a `TaskResult` with:',
            f'- `success`: Boolean indicating success',
            f'- `data`: Result data (if successful)',
            f'- `error`: Error message (if failed)',
            f'- `timestamp`: ISO timestamp',
            f'',
            f'## Testing',
            f'',
            f'```bash',
            f'python -m pytest tests/',
            f'```',
            f'',
            f'## License',
            f'',
            f'MIT',
        ]
        
        return '\n'.join(lines)
    
    def generate_config_py(self, agent_name: str, spec: dict) -> str:
        """Generate configuration module."""
        slug = self._slugify(agent_name)
        date_str = datetime.now().strftime("%Y-%m-%d")
        
        lines = [
            '#!/usr/bin/env python3',
            f'"""',
            f'Configuration module for {agent_name}.',
            f'',
            f'Generated by WORLD CEO on {date_str}',
            f'"""',
            f'',
            f'import os',
            f'from typing import Optional',
            f'from dataclasses import dataclass',
            f'',
            f'',
            f'@dataclass',
            f'class Config:',
            f'    """Configuration for {agent_name}."""',
            f'    ',
            f'    # Logging',
            f'    log_level: str = "INFO"',
            f'    ',
            f'    # Timeouts',
            f'    timeout: int = 30',
            f'    ',
            f'    # API Keys (loaded from environment)',
            f'    api_key: Optional[str] = None',
            f'    ',
            f'    # Feature flags',
            f'    enable_caching: bool = True',
            f'    enable_retries: bool = True',
            f'    max_retries: int = 3',
            f'    ',
            f'    @classmethod',
            f'    def from_env(cls) -> "Config":',
            f'        """Load configuration from environment variables."""',
            f'        return cls(',
            f'            log_level=os.getenv("{slug.upper()}_LOG_LEVEL", "INFO"),',
            f'            timeout=int(os.getenv("{slug.upper()}_TIMEOUT", "30")),',
            f'            api_key=os.getenv("{slug.upper()}_API_KEY"),',
            f'            enable_caching=os.getenv("{slug.upper()}_ENABLE_CACHING", "true").lower() == "true",',
            f'            enable_retries=os.getenv("{slug.upper()}_ENABLE_RETRIES", "true").lower() == "true",',
            f'            max_retries=int(os.getenv("{slug.upper()}_MAX_RETRIES", "3"))',
            f'        )',
            f'    ',
            f'    def validate(self) -> bool:',
            f'        """Validate configuration."""',
            f'        # TODO: Add validation logic',
            f'        return True',
        ]
        
        return '\n'.join(lines)
    
    def generate_utils_py(self, agent_name: str, spec: dict) -> str:
        """Generate utilities module."""
        slug = self._slugify(agent_name)
        date_str = datetime.now().strftime("%Y-%m-%d")
        
        lines = [
            '#!/usr/bin/env python3',
            f'"""',
            f'Utility functions for {agent_name}.',
            f'',
            f'Generated by WORLD CEO on {date_str}',
            f'"""',
            f'',
            f'import json',
            f'import logging',
            f'import time',
            f'from functools import wraps',
            f'from typing import Any, Callable, Optional',
            f'',
            f'logger = logging.getLogger("{slug}")',
            f'',
            f'',
            f'def retry(max_attempts: int = 3, delay: float = 1.0, backoff: float = 2.0):',
            f'    """',
            f'    Retry decorator with exponential backoff.',
            f'    ',
            f'    Args:',
            f'        max_attempts: Maximum number of attempts',
            f'        delay: Initial delay between attempts',
            f'        backoff: Multiplier for delay after each attempt',
            f'    """',
            f'    def decorator(func: Callable) -> Callable:',
            f'        @wraps(func)',
            f'        def wrapper(*args, **kwargs):',
            f'            attempt = 1',
            f'            current_delay = delay',
            f'            ',
            f'            while attempt <= max_attempts:',
            f'                try:',
            f'                    return func(*args, **kwargs)',
            f'                except Exception as e:',
            f'                    if attempt == max_attempts:',
            f'                        raise',
            f'                    ',
            f'                    logger.warning(f"Attempt {{attempt}} failed: {{e}}. Retrying in {{current_delay}}s...")',
            f'                    time.sleep(current_delay)',
            f'                    current_delay *= backoff',
            f'                    attempt += 1',
            f'            ',
            f'            return None  # Should never reach here',
            f'        ',
            f'        return wrapper',
            f'    return decorator',
            f'',
            f'',
            f'def safe_json_loads(data: str, default: Any = None) -> Any:',
            f'    """',
            f'    Safely load JSON with fallback default.',
            f'    ',
            f'    Args:',
            f'        data: JSON string',
            f'        default: Default value if parsing fails',
            f'        ',
            f'    Returns:',
            f'        Parsed JSON or default',
            f'    """',
            f'    try:',
            f'        return json.loads(data)',
            f'    except (json.JSONDecodeError, TypeError) as e:',
            f'        logger.warning(f"JSON parse error: {{e}}")',
            f'        return default',
            f'',
            f'',
            f'def truncate_string(s: str, max_length: int = 100, suffix: str = "...") -> str:',
            f'    """',
            f'    Truncate string to maximum length.',
            f'    ',
            f'    Args:',
            f'        s: Input string',
            f'        max_length: Maximum length',
            f'        suffix: Suffix to add if truncated',
            f'        ',
            f'    Returns:',
            f'        Truncated string',
            f'    """',
            f'    if len(s) <= max_length:',
            f'        return s',
            f'    return s[:max_length - len(suffix)] + suffix',
            f'',
            f'',
            f'def format_timestamp(dt: Optional[Any] = None) -> str:',
            f'    """',
            f'    Format timestamp as ISO string.',
            f'    ',
            f'    Args:',
            f'        dt: datetime object (default: now)',
            f'        ',
            f'    Returns:',
            f'        ISO formatted timestamp',
            f'    """',
            f'    from datetime import datetime',
            f'    ',
            f'    if dt is None:',
            f'        dt = datetime.now()',
            f'    ',
            f'    return dt.isoformat()',
        ]
        
        return '\n'.join(lines)
    
    def generate_test_py(self, agent_name: str, spec: dict) -> str:
        """Generate test suite."""
        slug = self._slugify(agent_name)
        class_name = self._classify(slug)
        date_str = datetime.now().strftime("%Y-%m-%d")
        
        lines = [
            '#!/usr/bin/env python3',
            f'"""',
            f'Test suite for {agent_name}.',
            f'',
            f'Generated by WORLD CEO on {date_str}',
            f'"""',
            f'',
            f'import pytest',
            f'from unittest.mock import Mock, patch',
            f'',
            f'from {slug}_skill import {class_name}Skill, TaskResult',
            f'',
            f'',
            f'class Test{class_name}Skill:',
            f'    """Test cases for {class_name}Skill."""',
            f'    ',
            f'    def setup_method(self):',
            f'        """Set up test fixtures."""',
            f'        self.skill = {class_name}Skill()',
            f'    ',
            f'    def test_initialization(self):',
            f'        """Test skill initialization."""',
            f'        assert self.skill.name == "{agent_name}"',
            f'        assert self.skill.version == "0.1.0"',
            f'    ',
            f'    def test_execute_success(self):',
            f'        """Test successful task execution."""',
            f'        # TODO: Update with actual task name',
            f'        result = self.skill.execute("example", {{"test": "data"}})',
            f'        ',
            f'        assert isinstance(result, TaskResult)',
            f'        assert result.success is True',
            f'        assert result.timestamp is not None',
            f'    ',
            f'    def test_execute_failure(self):',
            f'        """Test failed task execution."""',
            f'        # Test with non-existent task',
            f'        result = self.skill.execute("nonexistent_task")',
            f'        ',
            f'        assert isinstance(result, TaskResult)',
            f'        assert result.success is False',
            f'        assert result.error is not None',
            f'    ',
            f'    def test_health_check(self):',
            f'        """Test health check."""',
            f'        result = self.skill.health_check()',
            f'        ',
            f'        assert isinstance(result, TaskResult)',
            f'        assert result.success is True',
            f'        assert result.data is not None',
            f'    ',
            f'    def test_task_result_to_dict(self):',
            f'        """Test TaskResult serialization."""',
            f'        result = TaskResult(success=True, data={{"key": "value"}})',
            f'        data = result.to_dict()',
            f'        ',
            f'        assert data["success"] is True',
            f'        assert data["data"] == {{"key": "value"}}',
            f'        assert "timestamp" in data',
            f'',
            f'',
            f'class TestUtils:',
            f'    """Test utility functions."""',
            f'    ',
            f'    def test_retry_decorator(self):',
            f'        """Test retry decorator."""',
            f'        from {slug}_utils import retry',
            f'        ',
            f'        call_count = 0',
            f'        ',
            f'        @retry(max_attempts=3, delay=0.1)',
            f'        def flaky_function():',
            f'            nonlocal call_count',
            f'            call_count += 1',
            f'            if call_count < 3:',
            f'                raise ValueError("Temporary failure")',
            f'            return "success"',
            f'        ',
            f'        result = flaky_function()',
            f'        assert result == "success"',
            f'        assert call_count == 3',
            f'    ',
            f'    def test_safe_json_loads_valid(self):',
            f'        """Test safe JSON loading with valid input."""',
            f'        from {slug}_utils import safe_json_loads',
            f'        ',
            f'        result = safe_json_loads(\'{{"key": "value"}}\')',
            f'        assert result == {{"key": "value"}}',
            f'    ',
            f'    def test_safe_json_loads_invalid(self):',
            f'        """Test safe JSON loading with invalid input."""',
            f'        from {slug}_utils import safe_json_loads',
            f'        ',
            f'        result = safe_json_loads("invalid json", default=dict())',
            f'        assert result == dict()',
            f'',
            f'',
            f'if __name__ == "__main__":',
            f'    pytest.main([__file__, "-v"])',
        ]
        
        return '\n'.join(lines)
    
    def generate_requirements_txt(self, agent_name: str, spec: dict) -> str:
        """Generate requirements.txt."""
        date_str = datetime.now().strftime("%Y-%m-%d")
        
        lines = [
            f'# Requirements for {agent_name}',
            f'# Generated by WORLD CEO on {date_str}',
            f'',
            f'# Core dependencies',
            f'requests>=2.28.0',
            f'python-dotenv>=0.19.0',
            f'',
            f'# Testing',
            f'pytest>=7.0.0',
            f'pytest-cov>=3.0.0',
            f'',
            f'# Type checking',
            f'mypy>=0.950',
            f'',
            f'# Linting',
            f'flake8>=4.0.0',
            f'black>=22.0.0',
            f'',
            f'# Utilities',
            f'python-dateutil>=2.8.0',
        ]
        
        return '\n'.join(lines)
    
    def generate_readme_md(self, agent_name: str, spec: dict) -> str:
        """Generate README.md."""
        slug = self._slugify(agent_name)
        class_name = self._classify(slug)
        desc = spec.get("description", "No description provided.")
        skills = spec.get("skills", ["Core functionality"])
        date_str = datetime.now().strftime("%Y-%m-%d")
        
        skills_list = '\n'.join([f'- {skill}' for skill in skills])
        
        lines = [
            f'# {agent_name}',
            f'',
            f'{desc}',
            f'',
            f'## Features',
            f'',
            f'{skills_list}',
            f'',
            f'## Quick Start',
            f'',
            f'### Installation',
            f'',
            f'```bash',
            f'git clone https://github.com/openclaw-agent/{slug}.git',
            f'cd {slug}',
            f'pip install -r requirements.txt',
            f'```',
            f'',
            f'### Configuration',
            f'',
            f'Set environment variables:',
            f'',
            f'```bash',
            f'export {slug.upper()}_LOG_LEVEL=INFO',
            f'export {slug.upper()}_API_KEY=your_api_key',
            f'```',
            f'',
            f'### Usage',
            f'',
            f'```python',
            f'from {slug}_skill import {class_name}Skill',
            f'',
            f'skill = {class_name}Skill()',
            f'result = skill.execute("task", {{"param": "value"}})',
            f'```',
            f'',
            f'## Documentation',
            f'',
            f'- [Agent Instructions](AGENT.md)',
            f'- [Personality](SOUL.md)',
            f'- [Tools](TOOLS.md)',
            f'- [Improvement Cycles](HEARTBEAT.md)',
            f'',
            f'## Development',
            f'',
            f'```bash',
            f'# Run tests',
            f'pytest tests/',
            f'',
            f'# Run linting',
            f'flake8 {slug}_skill/',
            f'black {slug}_skill/',
            f'',
            f'# Type checking',
            f'mypy {slug}_skill/',
            f'```',
            f'',
            f'## License',
            f'',
            f'MIT License - See LICENSE file',
            f'',
            f'## Created By',
            f'',
            f'Generated by WORLD CEO v0.1 on {date_str}',
        ]
        
        return '\n'.join(lines)
    
    def generate_code(self, agent_name: str, spec: dict) -> CodePackage:
        """
        Generate complete code package for an agent.
        
        Args:
            agent_name: Name of the agent
            spec: Agent specification dictionary
            
        Returns:
            CodePackage with all generated files
        """
        logger.info(f"Generating code for agent: {agent_name}")
        
        return CodePackage(
            skill_py=self.generate_skill_py(agent_name, spec),
            skill_md=self.generate_skill_md(agent_name, spec),
            config_py=self.generate_config_py(agent_name, spec),
            utils_py=self.generate_utils_py(agent_name, spec),
            test_py=self.generate_test_py(agent_name, spec),
            requirements_txt=self.generate_requirements_txt(agent_name, spec),
            readme_md=self.generate_readme_md(agent_name, spec)
        )
    
    def write_code(self, agent_name: str, code: CodePackage, agent_dir: Optional[Path] = None) -> Dict[str, Path]:
        """
        Write generated code to files.
        
        Args:
            agent_name: Name of the agent
            code: CodePackage to write
            agent_dir: Optional specific directory
            
        Returns:
            Dictionary mapping file names to paths
        """
        slug = self._slugify(agent_name)
        
        if agent_dir is None:
            agent_dir = self.output_dir / slug
        agent_dir.mkdir(parents=True, exist_ok=True)
        
        # Create subdirectories
        skills_dir = agent_dir / "skills"
        skills_dir.mkdir(exist_ok=True)
        
        tests_dir = agent_dir / "tests"
        tests_dir.mkdir(exist_ok=True)
        
        scripts_dir = agent_dir / "scripts"
        scripts_dir.mkdir(exist_ok=True)
        
        files = {}
        
        # Write skill module
        skill_path = skills_dir / f"{slug}_skill.py"
        skill_path.write_text(code.skill_py)
        files["skill.py"] = skill_path
        logger.info(f"Written: {skill_path}")
        
        # Write SKILL.md
        skill_md_path = skills_dir / "SKILL.md"
        skill_md_path.write_text(code.skill_md)
        files["SKILL.md"] = skill_md_path
        logger.info(f"Written: {skill_md_path}")
        
        # Write config
        config_path = skills_dir / f"{slug}_config.py"
        config_path.write_text(code.config_py)
        files["config.py"] = config_path
        logger.info(f"Written: {config_path}")
        
        # Write utils
        utils_path = skills_dir / f"{slug}_utils.py"
        utils_path.write_text(code.utils_py)
        files["utils.py"] = utils_path
        logger.info(f"Written: {utils_path}")
        
        # Write tests
        test_path = tests_dir / f"test_{slug}.py"
        test_path.write_text(code.test_py)
        files["test.py"] = test_path
        logger.info(f"Written: {test_path}")
        
        # Write requirements
        req_path = agent_dir / "requirements.txt"
        req_path.write_text(code.requirements_txt)
        files["requirements.txt"] = req_path
        logger.info(f"Written: {req_path}")
        
        # Write README
        readme_path = agent_dir / "README.md"
        readme_path.write_text(code.readme_md)
        files["README.md"] = readme_path
        logger.info(f"Written: {readme_path}")
        
        # Write __init__.py
        init_path = skills_dir / "__init__.py"
        init_path.write_text(f'"""{agent_name} skill package."""\n')
        files["__init__.py"] = init_path
        
        return files


def main():
    """CLI entry point."""
    import argparse
    
    parser = argparse.ArgumentParser(description="Generate agent code")
    parser.add_argument("--spec", "-s", required=True, help="Agent spec JSON file")
    parser.add_argument("--output", "-o", help="Output directory")
    
    args = parser.parse_args()
    
    # Load spec
    with open(args.spec, 'r') as f:
        spec = json.load(f)
    
    # Generate code
    generator = CodeGenerator(output_dir=args.output)
    code = generator.generate_code(spec["name"], spec)
    files = generator.write_code(spec["name"], code)
    
    print(f"\nGenerated code for '{spec['name']}':")
    for name, path in files.items():
        print(f"  {name}: {path}")


if __name__ == "__main__":
    main()
